[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[project]
name = 'webmaus'
version = '0.1.0'
dependencies = [
    'requests',
    'lxml',
    'progressbar2',
    'soundfile',
]

